<a href="https://colab.research.google.com/github/AaravDB/Python_libraries/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a=np.array([1,2,3])
print(a,type(a))
print(a.shape)
b=np.array([a,a])
print(b.shape)
print(b)
c=np.zeros((2,2))
print(c)
d=np.ones((2,3))
print(d)
e=np.eye(2)
print(e)
f=np.random.random((2,3))
print(f)


[1 2 3] <class 'numpy.ndarray'>
(3,)
(2, 3)
[[1 2 3]
 [1 2 3]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0.]
 [0. 1.]]
[[0.89260994 0.74132991 0.24029487]
 [0.1410861  0.81026557 0.18959881]]


In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b=a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a)

77
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [ ]:
a = np.array([[[1,2], [3, 4], [5, 6]],[[7,8],[9,10],[11,12]]])
print(a)
# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0,0,0,1,1,1],[0,1,2,0,1,2],[0,1,0,1,0,1]])

# The above example of integer array indexing is equivalent to this:
#print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  4  5  8  9 12]


In [ ]:
z = np.array([1, 2], dtype=np.int64)
zer=np.zeros((1,2),dtype=np.int64)
print(zer.dtype)

int64


In [ ]:
x=[[1,2],[3,4]]
y=[[5,6],[7,8]]
print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))
print(np.dot(x,y))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))
print(np.sum(a,axis=2))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]
[[ 8 10]
 [12 14]
 [16 18]]
[[ 9 12]
 [27 30]]
[[ 3  7 11]
 [15 19 23]]
