<a href="https://colab.research.google.com/github/AaravDB/Python_libraries/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd


we can create a dataframe from a dictionary

In [15]:
dict1={
    "name":['a','b','c','d'],
    "marks":[1,2,3,None],
    "city":['e','f','g','h']
}

In [17]:
df=pd.DataFrame(dict1)
print(df,type(df))


  name  marks city
0    a    1.0    e
1    b    2.0    f
2    c    3.0    g
3    d    NaN    h <class 'pandas.core.frame.DataFrame'>


we can convert it to a csv

In [ ]:
df.to_csv('abc.csv',)
df.to_csv('abcd.csv',index=False)
df.head(2)
df.tail(2)


or read it from one

In [5]:
dfs=pd.read_csv('abcd.csv')
print(dfs.head(2))

FileNotFoundError: [Errno 2] No such file or directory: 'abcd.csv'

In [31]:
dfs['marks']

0    1.0
1    2.0
2    3.0
Name: marks, dtype: float64

we can create a dataframe from a numpy array

In [12]:
import numpy as np
npcreateddf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
npcreateddf.tail(5)


0         1         2         3         4
329  0.743752  0.676079  0.914953  0.388022  0.436329
330  0.647520  0.137494  0.343669  0.861735  0.535949
331  0.047660  0.177670  0.721765  0.233842  0.431316
332  0.016545  0.792589  0.634056  0.115920  0.607297
333  0.506884  0.330629  0.218203  0.254182  0.985059

In [ ]:
npcreateddf[0][0]=0.09

In [14]:
npcreateddf.head()

0         1         2         3         4
0  0.090000  0.496623  0.063401  0.260735  0.301578
1  0.642935  0.761032  0.505694  0.483874  0.963636
2  0.901340  0.642556  0.269112  0.693456  0.737582
3  0.868369  0.525662  0.332012  0.593362  0.691487
4  0.467547  0.725492  0.070888  0.782207  0.228003

or create a numpy array from a dataframe

In [15]:
b=npcreateddf.to_numpy()
print(b.shape)
print(b)

(334, 5)
[[0.09       0.49662285 0.06340061 0.26073523 0.30157829]
 [0.64293497 0.76103249 0.50569402 0.48387378 0.96363576]
 [0.90134011 0.64255575 0.26911175 0.69345645 0.73758219]
 ...
 [0.04765967 0.17766956 0.72176498 0.23384245 0.43131646]
 [0.01654542 0.79258865 0.63405585 0.11592022 0.60729685]
 [0.50688368 0.33062899 0.21820296 0.25418212 0.98505946]]


we can clean dataframes using pandas-including
empty cells
wrong values
wrong data formats
duplicates

empty treatment

In [37]:
a=pd.read_csv('abc.csv')
print(a)


   Unnamed: 0 name  marks city
0           0    a    1.0    e
1           1    b    2.0    f
2           2    c    3.0    g
3           3    d    NaN    h


In [38]:
a.dropna(inplace=True)
print(a)

   Unnamed: 0 name  marks city
0           0    a    1.0    e
1           1    b    2.0    f
2           2    c    3.0    g


In [51]:
dict2={
    "name":[None,'b','c','d'],
    "marks":[1,2,3,None],
    "city":['e','f','g','h']
}
b=pd.DataFrame(dict2)
print(b)
b.to_csv('abc.csv')

   name  marks city
0  None    1.0    e
1     b    2.0    f
2     c    3.0    g
3     d    NaN    h


In [61]:

B=pd.read_csv('abc.csv')
print(B)


   Unnamed: 0 name  marks city
0           0  NaN    1.0    e
1           1    b    2.0    f
2           2    c    3.0    g
3           3    d    NaN    h


In [60]:
B.fillna('b',inplace=True)
print(B)


   Unnamed: 0 name marks city
0           0    b   1.0    e
1           1    b   2.0    f
2           2    c   3.0    g
3           3    d     b    h


<ipython-input-60-e722d1486d52>:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'b' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  B.fillna('b',inplace=True)


In [80]:
C=pd.read_csv('abc.csv')
print(C)
C.fillna({'name':'a','marks':500,'city':'e'},inplace=True)
print(C)

   Unnamed: 0 name  marks city
0           0  NaN    1.0    e
1           1    b    2.0    f
2           2    c    3.0    g
3           3    d    NaN    h
   Unnamed: 0 name  marks city
0           0    a    1.0    e
1           1    b    2.0    f
2           2    c    3.0    g
3           3    d  500.0    h


In [72]:
x=C['marks'].median()
print(x)

2.5


wrong format treatment

In [ ]:
df['date']=pd.to_datetime(df['date'],format='mixed')

In [ ]:
#to remove the rows containing null values in a particular column
df.dropna(subset=['date'],inplace=True)

fixing wrong values(too large or too little)

In [81]:
C.loc[3,'marks']=5
print(C)

   Unnamed: 0 name  marks city
0           0    a    1.0    e
1           1    b    2.0    f
2           2    c    3.0    g
3           3    d    5.0    h


In [82]:
C['marks']=[2,3,4,6]
print(C)

   Unnamed: 0 name  marks city
0           0    a      2    e
1           1    b      3    f
2           2    c      4    g
3           3    d      6    h


In [84]:
C.loc[3,'marks']=5
print(C)


   Unnamed: 0 name  marks city
0           0    a      2    e
1           1    b      3    f
2           2    c      4    g
3           3    d      5    h


In [18]:
print(df)
for x in df.index:
  if df.loc[x,'marks']>2:
    df.loc[x,'marks']=2
print(df)

  name  marks city
0    a    1.0    e
1    b    2.0    f
2    c    3.0    g
3    d    NaN    h
  name  marks city
0    a    1.0    e
1    b    2.0    f
2    c    2.0    g
3    d    NaN    h


duplicate dealing

In [19]:
dict3={
    "name":['a','b','c','a'],
    "marks":[1,2,3,1],
    "city":['e','f','g','e']
}

In [24]:
df3=pd.DataFrame(dict3)
df3.drop_duplicates(inplace=True)
print(df3)

  name  marks city
0    a      1    e
1    b      2    f
2    c      3    g
